### ISSUE TITLE
The Programm which connects labVIEW to Proteus 

### ISSUE THREAD

**Issue by MostafaOsman144** [wbadry/MCT432-Hybrid-Control#1]
Eng. Walid,
The name of the program which connects labVIEW to Proteus is not mentioned in the slides and I don't remember its name. Could you please tell me the name ?

**Comment by wbadry** [comment]
> The name of the program which connects labVIEW to Proteus is not mentioned in the slides 

@MostafaOsman144 You can use any free virtual serial port emulator software like [this one](https://freevirtualserialports.com/) . I should've added it :blush:

**Comment by MostafaOsman144** [comment]
Thank you Eng. Walid :)

**Comment by wbadry** [comment]
You are welcome. Closed
